"""
pdf_generator.py — Generates a professional service agreement PDF with
e-signature placeholder blocks using reportlab.
"""

import io
import json
from datetime import datetime
from typing import Any, Dict, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ---------------------------------------------------------------------------
# Brand colours (mirrors the dark-theme palette, lightened for white paper)
# ---------------------------------------------------------------------------
BRAND_INDIGO = colors.HexColor("#4f46e5")
BRAND_INDIGO_LIGHT = colors.HexColor("#818cf8")
BRAND_GREEN = colors.HexColor("#16a34a")
GREY_900 = colors.HexColor("#111827")
GREY_700 = colors.HexColor("#374151")
GREY_500 = colors.HexColor("#6b7280")
GREY_200 = colors.HexColor("#e5e7eb")
GREY_100 = colors.HexColor("#f3f4f6")
WHITE = colors.white

PAGE_W, PAGE_H = A4
MARGIN = 20 * mm


def generate_contract_pdf(
    contract_id: str,
    negotiation_id: str,
    listing_title: str,
    service_type: str,
    terms_json: str,
    total_value: float,
    contract_created_at: datetime,
    seller_name: str,
    buyer_name: str,
    round_count: int,
    negotiation_completed_at: Optional[datetime],
) -> bytes:
    """
    Build and return raw PDF bytes for a service agreement contract.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title=f"Service Agreement — {listing_title}",
        author="NegotiAI Platform",
    )

    terms: Dict[str, Any] = {}
    try:
        terms = json.loads(terms_json)
    except Exception:
        pass

    styles = _build_styles()
    story = []

    # -----------------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------------
    story += _header(styles, listing_title, contract_id, contract_created_at)
    story.append(Spacer(1, 6 * mm))

    # -----------------------------------------------------------------------
    # Parties
    # -----------------------------------------------------------------------
    story.append(Paragraph("PARTIES TO THIS AGREEMENT", styles["section_title"]))
    story.append(Spacer(1, 3 * mm))
    story += _parties_table(seller_name, buyer_name, service_type, styles)
    story.append(Spacer(1, 6 * mm))

    # -----------------------------------------------------------------------
    # Negotiation summary
    # -----------------------------------------------------------------------
    story.append(Paragraph("NEGOTIATION SUMMARY", styles["section_title"]))
    story.append(Spacer(1, 3 * mm))
    story += _negotiation_summary(
        negotiation_id, round_count, negotiation_completed_at, styles
    )
    story.append(Spacer(1, 6 * mm))

    # -----------------------------------------------------------------------
    # Agreed terms
    # -----------------------------------------------------------------------
    story.append(Paragraph("AGREED TERMS", styles["section_title"]))
    story.append(Spacer(1, 3 * mm))
    story += _terms_table(terms, total_value, service_type, styles)
    story.append(Spacer(1, 6 * mm))

    # -----------------------------------------------------------------------
    # Boilerplate T&Cs
    # -----------------------------------------------------------------------
    story.append(Paragraph("TERMS AND CONDITIONS", styles["section_title"]))
    story.append(Spacer(1, 3 * mm))
    story += _terms_and_conditions(styles)
    story.append(Spacer(1, 8 * mm))

    # -----------------------------------------------------------------------
    # Signature blocks
    # -----------------------------------------------------------------------
    story.append(Paragraph("SIGNATURES", styles["section_title"]))
    story.append(Spacer(1, 4 * mm))
    story += _signature_blocks(seller_name, buyer_name, styles)

    # -----------------------------------------------------------------------
    # Footer note
    # -----------------------------------------------------------------------
    story.append(Spacer(1, 6 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GREY_200))
    story.append(Spacer(1, 2 * mm))
    story.append(
        Paragraph(
            "This document was generated by the <b>NegotiAI</b> AI-powered negotiation platform. "
            "Contract reference: <font color='#4f46e5'>" + contract_id + "</font>",
            styles["footer"],
        )
    )

    doc.build(story)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def _header(styles, listing_title: str, contract_id: str, created_at: datetime):
    """Logo band + document title + metadata row."""
    # Logo band
    logo_table = Table(
        [[Paragraph("NegotiAI", styles["logo"]), Paragraph("SERVICE AGREEMENT", styles["doc_type"])]],
        colWidths=[(PAGE_W - 2 * MARGIN) * 0.5, (PAGE_W - 2 * MARGIN) * 0.5],
    )
    logo_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), BRAND_INDIGO),
            ("TEXTCOLOR", (0, 0), (-1, -1), WHITE),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (0, -1), 14),
            ("RIGHTPADDING", (-1, 0), (-1, -1), 14),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ])
    )

    # Subtitle + meta
    meta_table = Table(
        [
            [
                Paragraph(listing_title, styles["contract_title"]),
                Paragraph(
                    f"Contract No: <b>{contract_id[:8].upper()}</b><br/>"
                    f"Date: <b>{created_at.strftime('%d %B %Y')}</b>",
                    styles["meta_right"],
                ),
            ]
        ],
        colWidths=[(PAGE_W - 2 * MARGIN) * 0.65, (PAGE_W - 2 * MARGIN) * 0.35],
    )
    meta_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), GREY_100),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING", (0, 0), (0, -1), 14),
            ("RIGHTPADDING", (-1, 0), (-1, -1), 14),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LINEBELOW", (0, 0), (-1, -1), 1, BRAND_INDIGO),
        ])
    )

    return [logo_table, Spacer(1, 0), meta_table]


def _parties_table(seller_name: str, buyer_name: str, service_type: str, styles):
    SERVICE_LABELS = {
        "advertising": "Advertising Space Provider",
        "staffing": "Staffing Agency",
        "sponsorship": "Event Organiser",
    }
    BUYER_LABELS = {
        "advertising": "Advertising Client",
        "staffing": "Client Company",
        "sponsorship": "Sponsor",
    }
    seller_role = SERVICE_LABELS.get(service_type, "Service Provider")
    buyer_role = BUYER_LABELS.get(service_type, "Client")

    tbl = Table(
        [
            [
                _party_cell("PARTY A — SELLER", seller_name, seller_role, styles),
                _party_cell("PARTY B — BUYER", buyer_name, buyer_role, styles),
            ]
        ],
        colWidths=[(PAGE_W - 2 * MARGIN - 4 * mm) * 0.5] * 2,
        spaceBefore=0,
    )
    tbl.setStyle(
        TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (0, -1), 0),
            ("RIGHTPADDING", (-1, 0), (-1, -1), 0),
            ("INNERGRID", (0, 0), (-1, -1), 0, WHITE),
            ("COLPADDING", (0, 0), (0, -1), 4),
        ])
    )
    return [tbl]


def _party_cell(header: str, name: str, role: str, styles):
    """Returns a Table used as a cell that looks like a card."""
    inner = Table(
        [
            [Paragraph(header, styles["party_header"])],
            [Paragraph(name, styles["party_name"])],
            [Paragraph(role, styles["party_role"])],
            [Spacer(1, 3 * mm)],
            [Paragraph("Registered on NegotiAI Platform", styles["party_meta"])],
        ],
        colWidths=[(PAGE_W - 2 * MARGIN) / 2 - 6 * mm],
    )
    inner.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), GREY_100),
            ("LINEABOVE", (0, 0), (-1, 0), 3, BRAND_INDIGO),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ])
    )
    return inner


def _negotiation_summary(negotiation_id: str, round_count: int, completed_at, styles):
    completed_str = completed_at.strftime("%d %B %Y, %H:%M UTC") if completed_at else "—"
    rows = [
        ["Negotiation ID", negotiation_id],
        ["Rounds to Agreement", str(round_count)],
        ["Completed", completed_str],
        ["Outcome", "✓  AGREEMENT REACHED"],
    ]
    tbl = Table(
        rows,
        colWidths=[60 * mm, PAGE_W - 2 * MARGIN - 60 * mm],
    )
    tbl.setStyle(
        TableStyle([
            ("FONT", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONT", (1, 0), (1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), GREY_700),
            ("TEXTCOLOR", (1, 0), (1, -2), GREY_900),
            ("TEXTCOLOR", (1, 3), (1, 3), BRAND_GREEN),
            ("FONT", (1, 3), (1, 3), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, GREY_100]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("LINEBELOW", (0, -1), (-1, -1), 0.5, GREY_200),
            ("LINEABOVE", (0, 0), (-1, 0), 0.5, GREY_200),
        ])
    )
    return [tbl]


def _terms_table(terms: dict, total_value: float, service_type: str, styles):
    """Build a terms table from whatever keys exist in the terms dict."""
    LABELS: Dict[str, str] = {
        "format": "Ad Format",
        "placement": "Placement",
        "duration_days": "Duration",
        "price_per_day": "Daily Rate",
        "start_date": "Start Date",
        "staff_count": "Staff Count",
        "daily_rate_per_person": "Rate per Person/Day",
        "role": "Role / Position",
        "funding_amount": "Funding Amount",
        "sponsorship_tier": "Sponsorship Tier",
        "deliverables": "Deliverables",
    }
    FORMATTERS: Dict[str, Any] = {
        "duration_days": lambda v: f"{v} days",
        "price_per_day": lambda v: f"${float(v):,.2f} / day",
        "daily_rate_per_person": lambda v: f"${float(v):,.2f} / person / day",
        "staff_count": lambda v: f"{v} people",
        "funding_amount": lambda v: f"${float(v):,.2f}",
    }

    rows = []
    for key, label in LABELS.items():
        val = terms.get(key)
        if val is None:
            continue
        fmt = FORMATTERS.get(key)
        display = fmt(val) if fmt else str(val)
        rows.append([label, display])

    # Total value — always last
    rows.append(["TOTAL CONTRACT VALUE", f"${total_value:,.2f}"])

    tbl = Table(
        rows,
        colWidths=[70 * mm, PAGE_W - 2 * MARGIN - 70 * mm],
    )
    style_cmds = [
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONT", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -2), 9),
        ("TEXTCOLOR", (0, 0), (0, -2), GREY_700),
        ("TEXTCOLOR", (1, 0), (1, -2), GREY_900),
        ("ROWBACKGROUNDS", (0, 0), (-1, -2), [WHITE, GREY_100]),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("LINEABOVE", (0, 0), (-1, 0), 0.5, GREY_200),
        # Total row styling
        ("FONT", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, -1), (-1, -1), 11),
        ("TEXTCOLOR", (0, -1), (-1, -1), BRAND_GREEN),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#f0fdf4")),
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, BRAND_GREEN),
        ("LINEBELOW", (0, -1), (-1, -1), 1.5, BRAND_GREEN),
    ]
    tbl.setStyle(TableStyle(style_cmds))
    return [tbl]


def _terms_and_conditions(styles):
    clauses = [
        ('<b>1. Binding Agreement.</b> This Service Agreement ("Agreement") constitutes a legally binding contract between the Seller and the Buyer upon execution by both parties.'),
        ("<b>2. Scope of Services.</b> The Seller agrees to deliver the services described in the Agreed Terms section above in accordance with the specifications negotiated through the NegotiAI platform."),
        ("<b>3. Payment.</b> The Buyer agrees to remit payment in full according to the agreed rate and duration. Payment is due within 14 days of contract execution unless otherwise agreed."),
        ("<b>4. Intellectual Property.</b> All creative assets and materials produced under this Agreement remain the property of the Buyer unless explicitly agreed otherwise."),
        ("<b>5. Confidentiality.</b> Both parties agree to keep the commercial terms of this Agreement confidential and not to disclose them to third parties without prior written consent."),
        ("<b>6. Termination.</b> Either party may terminate this Agreement with 7 days' written notice. Fees for services already rendered are non-refundable."),
        ("<b>7. Dispute Resolution.</b> Any disputes arising from this Agreement shall first be subject to good-faith mediation before either party pursues formal legal action."),
        ("<b>8. Governing Law.</b> This Agreement shall be governed by the laws of the jurisdiction in which the Seller is registered."),
    ]
    items = []
    for clause in clauses:
        items.append(Paragraph(clause, styles["clause"]))
        items.append(Spacer(1, 2 * mm))
    return items


def _signature_blocks(seller_name: str, buyer_name: str, styles):
    """Two side-by-side signature blocks."""
    sig_w = (PAGE_W - 2 * MARGIN - 10 * mm) / 2

    def _block(party_label: str, name: str) -> Table:
        rows = [
            [Paragraph(party_label, styles["sig_label"])],
            [Spacer(1, 12 * mm)],
            [HRFlowable(width=sig_w - 20 * mm, thickness=1, color=GREY_700)],
            [Paragraph("Signature", styles["sig_field_label"])],
            [Spacer(1, 6 * mm)],
            [HRFlowable(width=sig_w - 20 * mm, thickness=1, color=GREY_700)],
            [Paragraph("Full Name", styles["sig_field_label"])],
            [Spacer(1, 6 * mm)],
            [HRFlowable(width=sig_w - 20 * mm, thickness=1, color=GREY_700)],
            [Paragraph("Title / Position", styles["sig_field_label"])],
            [Spacer(1, 6 * mm)],
            [HRFlowable(width=sig_w - 20 * mm, thickness=1, color=GREY_700)],
            [Paragraph("Date", styles["sig_field_label"])],
            [Spacer(1, 4 * mm)],
            [Paragraph(f"On behalf of <b>{name}</b>", styles["sig_company"])],
        ]
        tbl = Table(rows, colWidths=[sig_w])
        tbl.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), GREY_100),
                ("LINEABOVE", (0, 0), (-1, 0), 3, BRAND_INDIGO),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ])
        )
        return tbl

    outer = Table(
        [[_block("SELLER", seller_name), Spacer(1, 10 * mm), _block("BUYER", buyer_name)]],
        colWidths=[sig_w, 10 * mm, sig_w],
    )
    outer.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return [outer]


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------


def _build_styles() -> dict:
    base = getSampleStyleSheet()
    s = {}

    def ps(name, **kw) -> ParagraphStyle:
        return ParagraphStyle(name, parent=base["Normal"], **kw)

    s["logo"] = ps("logo", fontSize=18, fontName="Helvetica-Bold", textColor=WHITE, alignment=TA_LEFT)
    s["doc_type"] = ps("doc_type", fontSize=10, fontName="Helvetica-Bold", textColor=colors.HexColor("#c7d2fe"), alignment=TA_RIGHT)
    s["contract_title"] = ps("contract_title", fontSize=13, fontName="Helvetica-Bold", textColor=GREY_900, alignment=TA_LEFT)
    s["meta_right"] = ps("meta_right", fontSize=8, fontName="Helvetica", textColor=GREY_700, alignment=TA_RIGHT)
    s["section_title"] = ps("section_title", fontSize=8, fontName="Helvetica-Bold", textColor=BRAND_INDIGO, spaceBefore=0, spaceAfter=0, letterSpacing=1)
    s["party_header"] = ps("party_header", fontSize=7, fontName="Helvetica-Bold", textColor=BRAND_INDIGO)
    s["party_name"] = ps("party_name", fontSize=11, fontName="Helvetica-Bold", textColor=GREY_900)
    s["party_role"] = ps("party_role", fontSize=8, fontName="Helvetica", textColor=GREY_700)
    s["party_meta"] = ps("party_meta", fontSize=7, fontName="Helvetica-Oblique", textColor=GREY_500)
    s["clause"] = ps("clause", fontSize=8, fontName="Helvetica", textColor=GREY_700, leading=12)
    s["sig_label"] = ps("sig_label", fontSize=8, fontName="Helvetica-Bold", textColor=BRAND_INDIGO)
    s["sig_field_label"] = ps("sig_field_label", fontSize=7, fontName="Helvetica", textColor=GREY_500)
    s["sig_company"] = ps("sig_company", fontSize=8, fontName="Helvetica", textColor=GREY_700)
    s["footer"] = ps("footer", fontSize=7, fontName="Helvetica-Oblique", textColor=GREY_500, alignment=TA_CENTER)
    return s
